# Generated by Django 5.2.14 on 2026-06-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('council_area', models.CharField(blank=True, max_length=120)),
                ('utilities_recovered_via_rent', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for review'), ('sent', 'Sent to tenant')], default='draft', max_length=20)),
                ('utility_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('council_increase_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proposed_weekly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shortfall_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_runs', to='reporting.property')),
            ],
            options={
                'ordering': ['-report_year', 'property__name'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank statement PDF'), ('property_manager', 'Property manager statement'), ('council_report', 'Council rental report'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(help_text='Path, filename or note describing where the source document came from.', max_length=255)),
                ('parser_hint', models.CharField(blank=True, help_text='Optional parser name, such as pdf2csv, for later ingestion work.', max_length=120)),
                ('processing_state', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reporting.reportingrun')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tenancy_start', models.DateField()),
                ('tenancy_end', models.DateField(blank=True, null=True)),
                ('weekly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='reporting.property')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='reportingrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_runs', to='reporting.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingrun',
            unique_together={('tenant', 'report_year')},
        ),
    ]
