# Generated by Django 5.2.14 on 2026-06-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='source_documents/'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='document_type',
            field=models.CharField(choices=[('bank_statement', 'Bank statement PDF'), ('property_manager', 'Property manager statement'), ('utility_statement', 'Utility statement'), ('council_report', 'Council rental report'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='reference',
            field=models.CharField(blank=True, help_text='Path, filename or note describing where the source document came from.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='reporting_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reporting.reportingrun'),
        ),
    ]
