# Generated by Django 5.2.14 on 2026-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_sourcedocument_upload_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WEGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.PositiveIntegerField(unique=True)),
                ('property_management', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hot_water', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('co2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('land_tax', models.DecimalField(decimal_places=2, default=0, help_text='From the separate council land tax statement.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_year'],
            },
        ),
    ]
