# Generated by Django 5.2.14 on 2026-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_add_bank_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wegreport',
            name='monthly_heating_advance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly Heizkostenvorschuss per tenancy agreement.', max_digits=10),
        ),
        migrations.AddField(
            model_name='wegreport',
            name='monthly_operating_advance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly Betriebskosten Vorauszahlung per tenancy agreement.', max_digits=10),
        ),
        migrations.AddField(
            model_name='wegreport',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly Kaltmiete per tenancy agreement.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='classification',
            field=models.CharField(blank=True, choices=[('tenant_rent', 'Tenant — Rent'), ('tenant_operating', 'Tenant — Operating advance'), ('tenant_heating', 'Tenant — Heating advance'), ('tenant_shortfall', 'Tenant — Shortfall payment'), ('management', 'Management'), ('land_tax', 'Land tax'), ('affiliations', 'Affiliations')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='statementpattern',
            name='classification',
            field=models.CharField(choices=[('tenant_rent', 'Tenant — Rent'), ('tenant_operating', 'Tenant — Operating advance'), ('tenant_heating', 'Tenant — Heating advance'), ('tenant_shortfall', 'Tenant — Shortfall payment'), ('management', 'Management'), ('land_tax', 'Land tax'), ('affiliations', 'Affiliations')], default='tenant_rent', max_length=30),
        ),
    ]
