# Generated by Django 5.2.14 on 2026-06-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_add_shortfall_and_monthly_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
