# Generated by Django 5.2.14 on 2026-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_property_owner_address_property_owner_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wegreport',
            name='prior_year_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Optional prior-year Nebenkosten balance carried into this year's invoice.", max_digits=10),
        ),
    ]
