# Generated by Django 5.2.14 on 2026-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_wegreport_prior_year_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentIncreasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.PositiveIntegerField(unique=True)),
                ('projected_annual_maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projected_annual_utility_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mietspiegel_weekly_cold_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_increase_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_year'],
            },
        ),
    ]
